In [1]:
import pandas as pd
import os

In [4]:
def usa_f_open (path,sep):
    data3 = open (path,"r")
    cols = data3.readline().strip().split(sep)
    n_cols = len (cols)
    counter = 0
    main_dict ={}
    for col in cols:
        main_dict[col]=[]
        
    for line in data3:
        values = line.strip().split(sep)
        for i in range (len(cols)):
            main_dict [cols[i]].append(values[i])
        counter +=1
        
    print("El data set tiene %d filas y %d columnas"%(counter, n_cols))
    df = pd.DataFrame(main_dict)
    return df

In [5]:
df_prueba= usa_f_open("../datasets/customer-churn-model/Customer Churn Model.csv",',')
df_prueba.head(3)

El data set tiene 3333 filas y 21 columnas

,"""State",Account Length,Area Code,"Churn?""",CustServ Calls,Day Calls,Day Charge,Day Mins,Eve Calls,Eve Charge,...,Int'l Plan,Intl Calls,Intl Charge,Intl Mins,Night Calls,Night Charge,Night Mins,Phone,VMail Message,VMail Plan
0,"""KS",128,415,"False.""",1,110,45.070000,265.100000,99,16.780000,...,no,3,2.700000,10.000000,91,11.010000,244.700000,382-4657,25,yes
1,"""OH",107,415,"False.""",1,123,27.470000,161.600000,103,16.620000,...,no,3,3.700000,13.700000,103,11.450000,254.400000,371-7191,26,yes
2,"""NJ",137,415,"False.""",0,114,41.380000,243.400000,110,10.300000,...,no,5,3.290000,12.200000,104,7.320000,162.600000,358-1921,0,no